CREATE TABLE volunteer_options (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  imageUrl VARCHAR(255) NOT NULL,
  date VARCHAR(50) NOT NULL,
  location VARCHAR(255) NOT NULL
);